public class ReadMe {

    /*

        1) THIS PROJECT WILL FAIL UNTIL YOU WRITE ALL THE METHODS

        2) THIS PROJECT IS ABOUT THE USER BUYING AN ITEM FROM AN ONLINE SHOPPING WEBSITE

        3) FIRST START WITH Settings package and UserSettings class

            THEN ITEMS > USERNAMEANDPASSWORD > ADDRESS this is my suggestion you can start from any class.

        4) ALL THE ADDITIONAL COMMENTS ARE IN THE CLASSES

        5) TO CHECK YOUR CODES ARE CORRECT OR NOT, YOU WILL USE Test1 CLASS. TEST1 CLASS AND YOURTEST CLASS ARE NOT RELATED TO EACH OTHER.

        6) AFTER YOU FINISHED ALL PARTS IN THE CLASSES, IN THE YourTest CLASS YOU ARE EXPECTED TO CREATE YOUR OWN TEST CASES FOR EACH POSSIBILITY OF THE
        METHODS(setUsername AND setPassword) IN THE UserNameAndPassword CLASS.
     */

}
